//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreWithEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductId { get; set; }
        public int ClientId { get; set; }
        public int ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Email { get; set; }
    
        public virtual Clients Clients { get; set; }

        public Products(int clientId, int productCode, string productName, string email)
        {
            ClientId = clientId;
            ProductCode = productCode;
            ProductName = productName;
            Email = email;
        }

        public Products()
        {
        }
    }
}
